include common.mk

$(RPM): $(GATEKEEPER)
	mkdir -p dist/package
	install $(GATEKEEPER) dist/package
	fpm \
	  -p $(RPM) \
	  -s dir \
	  -t rpm \
	  --name $(RPM_NAME) \
	  --version $(VERSION) \
	  --iteration $(ITERATION) \
	  --architecture x86_64 \
	  --force \
	  -C dist/package \
	  .
